nodeLinker: node-modules
enableGlobalCache: true
nmMode: hardlinks-local

enableImmutableInstalls: false
checksumBehavior: update

logFilters:
  - code: YN0002
    level: discard
  - code: YN0086
    level: discard